const portfolio = {
  name: "Om Kumar",
  title: "User Experience Designer",
  heroGreeting: "Hello, from the designer's desk.",
  heroCyclePrefix: "UX designer with a focus on",
  heroCycleWords: ["decision-first dashboards", "0-to-1 strategy", "the quiet UX", "AI-native products", "human-in-the-loop UX", "design systems that scale", "agentic interfaces"],
  tagline: "Thoughtful",
  taglineAccent: "by",
  taglineEnd: "design",
  heroSubtitle: "Making complex things simple to create clear, efficient experiences that drive results.",
  about: "I'm a UX designer with a focus on systems thinking and interface clarity. I believe good design disappears — it just works. Currently building at ConveGenius.AI.",
  statement: "Designer who codes, coder who thinks in strategy, strategist who ships.",
  bioParagraphs: [
    "I've been a designer since 2022. Initially drawn to visual design — crafting interfaces, replicating shots from Dribbble just to see if I could pull them off. What started as curiosity about making things look good slowly turned into something deeper.",
    "Over time, I found myself more interested in design systems and the spaces where design meets engineering. I love creating order, consistency, and scalable foundations. I've designed for governance, education, and healthcare — and I find myself most engaged when thinking about how systems can scale without breaking.",
  ],
  email: "om.kumar@convegenius.ai",
  linkedin: "https://linkedin.com/in/om-kumar",
  behance: "https://behance.net/om-kumar",
  workIntro: ["Hey! I'm a UX designer based in India.", "I'm currently building at ConveGenius.AI ✌️"],
  workHeading: "Handpicked",
  workHeadingAccent: "highlights",
  workDesc: "A selection of shipped and concept work from the last few years.",

  skills: [
    "Interaction Design", "Design Systems", "Figma", "Prototyping",
    "Wireframing", "Visual Design", "User Research", "Usability Testing",
    "Information Architecture", "ProtoPie", "Adobe CC", "Figma Make",
  ],

  // Populated at runtime from Supabase
  experience: [
    {
      role: "Senior UX Designer",
      company: "ConveGenius.AI",
      url: "https://convegenius.com/",
      period: "Sep 2025 — Present",
      location: "Noida",
      tags: ["EdTech", "AI", "Design Systems"],
      logoGradient: "linear-gradient(135deg,#4f46e5 0%,#7c3aed 100%)",
      logoId: "convegenius",
      points: [
        "Increasing user experience, enhancing usability and optimizing workflows of tech-based solutions for optimum educational impact.",
        "Leading the development and implementation of a token-based design system, improving consistency and scalability across multiple platforms.",
      ],
    },
    {
      role: "Associate UX Designer",
      company: "Samagra",
      url: "https://samagragovernance.in/",
      period: "Jan 2023 — Aug 2025",
      location: "New Delhi",
      tags: ["GovTech", "Research", "Product"],
      logoGradient: "linear-gradient(135deg,#ea580c 0%,#f59e0b 100%)",
      logoId: "samagra",
      logoUrl: "https://samagragovernance.in/static/Samagra_Logo_updated-f59ec74c713638ada10b837a71238eaa.svg",
      points: [
        "Multiple product and design thinking along with on-ground research resulting in accelerated usage of app and website.",
        "Worked on improving user interfaces for high-stake civic platforms including Kumbh Sah'AIyak and Bharat Sah'AIyak (now part of Krutrim-OLA).",
        "Implemented user and stakeholder feedback, reworked friction points, and consequently improved user experience across products.",
      ],
    },
    {
      role: "UX Designer",
      company: "IQ-Line",
      url: "https://iqline.co.in/",
      period: "Apr 2025 — Sep 2025",
      location: "New Delhi · Part-Time",
      tags: ["Healthcare", "LIMS", "B2B"],
      logoGradient: "linear-gradient(135deg,#0891b2 0%,#0d9488 100%)",
      logoId: "iqline",
      points: [
        "Led the development and implementation of a token-based design system, improving consistency and scalability across multiple platforms.",
        "Led the UI redesign for a LIMS, enhancing usability and optimizing workflows for healthcare professionals.",
        "Designed and developed the user interface for a new blood sample transfer system, improving the tracking and management of critical medical samples.",
        "Coordinated with healthcare professionals to gather insights and define requirements, ensuring alignment with medical standards and user needs.",
      ],
    },
  ],

  shoutouts: [
    {
      quote: "Om's designs are always clear and easy to implement. We rarely had to go back and forth, which made development significantly smoother.",
      name: "Arjun Mehta",
      role: "Frontend Engineer",
      company: "ConveGenius.AI",
      initials: "AM",
    },
    {
      quote: "Working with Om felt seamless. He thinks in systems — every decision he made scaled well across the product and saved us rework down the line.",
      name: "Priya Nair",
      role: "Product Manager",
      company: "Samagra",
      initials: "PN",
    },
    {
      quote: "Om approaches design with strong strategic thinking and a clear sense of direction. His instinct for what users actually need is sharp.",
      name: "Rahul Verma",
      role: "Engineering Lead",
      company: "IQ-Line",
      initials: "RV",
    },
    {
      quote: "The token system Om built for us became the foundation every team now works from. It's one of those rare pieces of work that keeps giving.",
      name: "Sneha Kulkarni",
      role: "Design Lead",
      company: "Samagra",
      initials: "SK",
    },
    {
      quote: "Om is the kind of designer who makes engineers feel heard. He cares about feasibility as much as aesthetics — genuinely great to work with.",
      name: "Dev Sharma",
      role: "Full-Stack Developer",
      company: "ConveGenius.AI",
      initials: "DS",
    },
  ],

  carousels: [
    {
      id: "c1",
      title: "Process",
      slides: [
        { label: "Research & Discovery", bg: "#f0ede8" },
        { label: "Sketching & Ideation", bg: "#e8edf0" },
        { label: "High-fidelity Mockups", bg: "#ede8f0" },
        { label: "Handoff & QA", bg: "#e8f0ec" },
      ],
    },
    {
      id: "c2",
      title: "Inspiration",
      slides: [
        { label: "Typography Studies", bg: "#f5f3ef" },
        { label: "Color Explorations", bg: "#eff3f5" },
        { label: "Layout Patterns", bg: "#f3eff5" },
        { label: "Motion References", bg: "#eff5f2" },
      ],
    },
    {
      id: "c3",
      title: "Tools & Workspace",
      slides: [
        { label: "Figma Workspace", bg: "#f0ede8" },
        { label: "Component Library", bg: "#e8edf0" },
        { label: "Design Tokens", bg: "#ede8f0" },
        { label: "Documentation", bg: "#e8f0ec" },
      ],
    },
  ],

  skillGroups: [
    {
      num: "01",
      name: "Design Process",
      gradient: "linear-gradient(135deg, #b85c38 0%, #e8814d 100%)",
      skills: ["User Research", "Interaction Design", "Usability Testing", "Prototyping", "Wireframing", "Visual Design"],
    },
    {
      num: "02",
      name: "Systems",
      gradient: "linear-gradient(135deg, #1a6b4a 0%, #34a870 100%)",
      skills: ["Design Systems", "Information Architecture", "Design Tokens", "Component Libraries", "Pattern Libraries"],
    },
    {
      num: "03",
      name: "Tools & Stack",
      gradient: "linear-gradient(135deg, #4338ca 0%, #818cf8 100%)",
      skills: ["Figma", "Figma Make", "ProtoPie", "Adobe CC", "Notion", "Linear"],
    },
  ],

  capabilities: [
    {
      num: "01",
      title: "Structuring Complex Products",
      description: "Taking messy ideas, constraints, and edge cases — and turning them into clear product structures that actually make sense in the real world.",
    },
    {
      num: "02",
      title: "Designing User Behavior",
      description: "Designing flows that guide decisions, reduce friction, and help users move forward with clarity, even in complex scenarios.",
    },
    {
      num: "03",
      title: "Delivering Real-World Systems",
      description: "Building and shipping products that hold up under real usage, real constraints, and real users — not just ideal conditions.",
    },
  ],

  capDesc: [
    "Approaches I use to understand complex systems and turn requirements into concrete product decisions.",
    "A set of capabilities that connects strategy, structure, and experience to build clearer, more reliable products.",
  ],

  capBlobs: [
    { label: "Design Systems", color: "#c5b8f8", rotate: -12 },
    { label: "Interaction Design", color: "#d4efb8", rotate: 8 },
    { label: "User Research", color: "#f8d8b8", rotate: -5 },
    { label: "Prototyping", color: "#b8e4f8", rotate: 14 },
    { label: "Visual Design", color: "#f8b8d4", rotate: -18 },
  ],

  projects: [
    {
      id: "01",
      status: "shipped",
      title: "Dashboard Redesign",
      category: "Product Design",
      year: "2025",
      description: "Simplified a complex analytics dashboard — reduced cognitive load by 40% through progressive disclosure and a tighter information hierarchy.",
      tags: ["UX", "Data Viz", "Design Systems"],
      color: "#f0ede8",
      iconGradient: "linear-gradient(135deg,#3a7bd5,#00d2ff)",
      accentColor: "#3a7bd5",
      detail: {
        role: "Lead Product Designer",
        challenge: "The existing dashboard showed 40+ metrics simultaneously with no hierarchy. Users were making decisions from the wrong data because everything looked equally important — there was no signal, only noise.",
        outcome: "A phased dashboard that surfaces the 3 most critical KPIs upfront, with progressive drill-down to secondary metrics. Shipped in Q2 2025 to 2,000+ daily active users.",
        stats: [
          { value: "40%", label: "Cognitive load reduced" },
          { value: "3×", label: "Faster decision time" },
          { value: "94%", label: "User satisfaction" },
        ],
        frames: [
          { type: "desktop", label: "Overview — primary KPIs" },
          { type: "desktop", label: "Drill-down — metrics detail" },
          { type: "mobile", label: "Mobile companion view" },
        ],
        recruiter: {
          timeline: "2025 · Q2 launch",
          liveAt: null,
          domain: "Analytics · B2B SaaS · Data visualization",
          platform: "Web app",
          team: "Solo designer · 8 engineers · 1 PM",
          problem: "The existing dashboard showed 40+ metrics simultaneously with no hierarchy. Users were making decisions from the wrong data because everything looked equally important.",
          shipped: "A phased dashboard surfacing the 3 most critical KPIs upfront, with progressive drill-down. Shipped to 2,000+ daily active users in Q2 2025.",
          owned: ["UX strategy", "Research", "IA", "Flows", "Wireframing", "Visual design", "Prototyping", "Dev handoff"],
          bullets: [
            "Lead Product Designer on a B2B analytics dashboard used by 2,000+ daily active users.",
            "Reduced cognitive load by 40% through restructured information hierarchy and progressive disclosure.",
            "Designed a phased KPI system surfacing signal over noise — 3 critical metrics shown upfront.",
            "Cut decision-making time by 3× through clearer data presentation and contextual drill-downs.",
            "Shipped Q2 2025 with 94% user satisfaction post-launch.",
          ],
        },
      },
    },
    {
      id: "02",
      status: "shipped",
      title: "Component Library",
      category: "Design Systems",
      year: "2025",
      description: "Built a shared component library spanning 60+ components across web and mobile, used by a team of 12 engineers.",
      tags: ["Figma", "Tokens", "Documentation"],
      color: "#e8edf0",
      iconGradient: "linear-gradient(135deg,#7f53ac,#647dee)",
      accentColor: "#7f53ac",
      detail: {
        role: "Design Systems Lead",
        challenge: "The product had grown across 4 separate surfaces with no shared language. Every new feature required re-solving solved problems, and visual inconsistency was eroding user trust.",
        outcome: "A single source of truth — 60+ components, design tokens, and written usage guidelines — that cut new feature design time from days to hours.",
        stats: [
          { value: "60+", label: "Components documented" },
          { value: "12", label: "Engineers onboarded" },
          { value: "70%", label: "Faster feature design" },
        ],
        frames: [
          { type: "wide", label: "Token system overview" },
          { type: "desktop", label: "Component documentation page" },
          { type: "mobile", label: "Mobile component variants" },
        ],
        recruiter: {
          timeline: "2025 · Ongoing",
          liveAt: null,
          domain: "Design Systems · Multi-surface product",
          platform: "Web app · Mobile app",
          team: "Solo designer · 12 engineers",
          problem: "The product had grown across 4 separate surfaces with no shared language. Every new feature required re-solving solved problems — visual inconsistency was eroding user trust.",
          shipped: "A single source of truth — 60+ components, design tokens, and written usage guidelines that cut new feature design time from days to hours.",
          owned: ["Design systems", "Design tokens", "Component architecture", "Documentation", "Figma", "Engineer onboarding"],
          bullets: [
            "Design Systems Lead, building a shared component library for a team of 12 engineers.",
            "60+ components documented with design tokens and written usage guidelines.",
            "Reduced new feature design time by 70% through standardised, reusable patterns.",
            "Eliminated visual inconsistency across 4 product surfaces with a single source of truth.",
            "Onboarded the full engineering team in under a week using structured documentation.",
          ],
        },
      },
    },
    {
      id: "03",
      status: "shipped",
      title: "Onboarding Flow",
      category: "UX / Product",
      year: "2024",
      description: "Redesigned a 12-step onboarding into a conversational 4-step flow. Increased activation rate from 31% to 67%.",
      tags: ["UX Research", "Prototyping", "A/B Testing"],
      color: "#ede8f0",
      iconGradient: "linear-gradient(135deg,#f7971e,#ffd200)",
      accentColor: "#f7971e",
      detail: {
        role: "UX Designer",
        challenge: "A 12-step onboarding was losing 69% of new users before they reached their first value moment. Exit interviews revealed confusion about what the product actually did.",
        outcome: "Conversational 4-step flow that front-loads value and defers non-critical setup. Activation rate more than doubled from 31% to 67% in the first 30 days post-launch.",
        stats: [
          { value: "67%", label: "Activation rate (was 31%)" },
          { value: "4", label: "Steps (was 12)" },
          { value: "2.1×", label: "Increase in day-7 retention" },
        ],
        frames: [
          { type: "mobile", label: "Welcome — step 1 of 4" },
          { type: "mobile", label: "Goal setting — step 2 of 4" },
          { type: "desktop", label: "First value moment" },
        ],
        recruiter: {
          timeline: "2024 · 30 days post-launch",
          liveAt: null,
          domain: "Growth · Onboarding · SaaS activation",
          platform: "Web app · Mobile",
          team: "Solo designer · 2 engineers · 1 PM",
          problem: "A 12-step onboarding was losing 69% of new users before they reached their first value moment. Exit interviews revealed confusion about what the product actually did.",
          shipped: "A conversational 4-step flow front-loading value and deferring non-critical setup — activation rate doubled from 31% to 67% in the first 30 days.",
          owned: ["UX research", "User interviews", "Flows", "Wireframing", "Prototyping", "A/B testing", "Dev handoff"],
          bullets: [
            "UX Designer on a SaaS onboarding redesign that doubled the activation rate.",
            "Conducted exit interviews to identify where and why 69% of new users dropped off.",
            "Redesigned a 12-step onboarding into a conversational 4-step flow that front-loads value.",
            "Activation rate increased from 31% to 67% in the first 30 days post-launch.",
            "Day-7 retention improved 2.1× as users reached their first value moment faster.",
          ],
        },
      },
    },
    {
      id: "04",
      status: "shipped",
      title: "Brand Identity",
      category: "Visual Design",
      year: "2024",
      description: "Created a cohesive visual identity for an edtech startup — logo, typography, color, and motion language.",
      tags: ["Branding", "Motion", "Typography"],
      color: "#e8f0ec",
      iconGradient: "linear-gradient(135deg,#11998e,#38ef7d)",
      accentColor: "#11998e",
      detail: {
        role: "Visual Designer",
        challenge: "An early-stage edtech startup had strong product ideas but no visual language to match. Their pitch deck used 5 different fonts and every screen felt like a different product.",
        outcome: "A complete identity system: wordmark, type scale, color palette, illustration style, and motion principles — all documented for handoff to an in-house team.",
        stats: [
          { value: "1", label: "Cohesive design language" },
          { value: "3", label: "Weeks from brief to delivery" },
          { value: "5×", label: "Increase in brand mentions" },
        ],
        frames: [
          { type: "wide", label: "Brand board — color & type" },
          { type: "desktop", label: "Marketing landing page" },
          { type: "mobile", label: "App icon & splash screen" },
        ],
        recruiter: {
          timeline: "2024 · 3-week sprint",
          liveAt: null,
          domain: "Brand Identity · EdTech · Visual design",
          platform: "Marketing site · App · Pitch deck",
          team: "Solo designer · CEO · 1 engineer",
          problem: "An early-stage edtech startup had strong product ideas but no visual language. Their pitch deck used 5 different fonts and every screen felt like a different product.",
          shipped: "A complete identity system — wordmark, type scale, color palette, illustration style, and motion principles — all documented for handoff to an in-house team.",
          owned: ["Brand strategy", "Logo design", "Typography", "Color system", "Motion principles", "Documentation"],
          bullets: [
            "Visual Designer on a full brand identity system for an early-stage edtech startup.",
            "Delivered wordmark, type scale, color palette, illustration style, and motion principles in 3 weeks.",
            "Resolved visual inconsistency across 5 mismatched fonts and disjointed screens.",
            "Documented the entire system for handoff — zero dependency on me post-delivery.",
            "Brand mentions increased 5× in the 3 months following launch.",
          ],
        },
      },
    },
    {
      id: "05",
      status: "coming-soon",
      title: "AI Design Toolkit",
      category: "Product Design",
      year: "2025",
      description: "A design system extension for AI-generated UI — bridging LLM output with consistent, accessible components.",
      tags: ["AI", "Design Systems", "Research"],
      color: "#e8eaf0",
      accentColor: "#6366f1",
    },
  ],
};
